### ISSUE TITLE
Spelling mistake oauth_helper.refesh()

### ISSUE THREAD

**Issue by TylerCarberry** [avinassh/prawoauth2#1]
The method is refesh() instead of refresh()

**Comment by avinassh** [comment]
hey @TylerCarberry, thank you very much. I have fixed it :smile:

**Comment by TylerCarberry** [comment]
You are still calling refesh on line 52 of PrawOAuth2Mini.py

**Comment by avinassh** [comment]
Oops, this is embarrassing. Fixed it! Thanks again :)
