### ISSUE TITLE
praw rate_limit still happening

### ISSUE THREAD

**Issue by ben-pr-p** [avinassh/prawoauth2#11]
I believe I have correctly implemented PrawOAuth2 server once and PrawOAuth2Mini, but my reddit client is still sleeping with praw's default rate_limit function. 

Is there a way to circumvent this, or should praw do that automatically? If I do OAuth2 correctly, I get 60 requests per minute, and there's no need to sleep for 2 seconds after every request, right?

Thanks

**Comment by avinassh** [comment]
I think I somehow missed to answer this. Rate limiting is handled by praw
